package techguns.client.models.guns;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.block.model.ItemCameraTransforms.TransformType;
import net.minecraft.entity.Entity;
import techguns.client.models.ModelMultipart;

public class ModelAS50 extends ModelMultipart{
	 //fields
   ModelRenderer Grip1;
   ModelRenderer Trigger01;
   ModelRenderer Trigger02;
   ModelRenderer MuzzleFront2;
   ModelRenderer Magazine01;
   ModelRenderer Trigger03;
   ModelRenderer MagHolder;
   ModelRenderer CheekRest;
   ModelRenderer LowerTrigger;
   ModelRenderer Magazine02;
   ModelRenderer Magazine03;
   ModelRenderer MidRailPart1;
   ModelRenderer UpperBarrel;
   ModelRenderer BarrelBigPart;
   ModelRenderer Barrel;
   ModelRenderer ReceiverTop;
   ModelRenderer BarrelBigPartTop;
   ModelRenderer ScopeMount4;
   ModelRenderer BarrelFrontPartBottom;
   ModelRenderer MidRailPart2;
   ModelRenderer MidRailPart3;
   ModelRenderer MidRailPart4;
   ModelRenderer MidRailPartTop;
   ModelRenderer MidRailPartFront;
   ModelRenderer BarrelMidPartTop;
   ModelRenderer BarrelMidPart01;
   ModelRenderer BarrelMidPartBottom;
   ModelRenderer ScopeFront;
   ModelRenderer BarrelFrontPart01;
   ModelRenderer MuzzleFront3;
   ModelRenderer MuzzleFront;
   ModelRenderer Muzzle05;
   ModelRenderer UpperTrigger;
   ModelRenderer StockBack02;
   ModelRenderer StockFlip;
   ModelRenderer StockBack01;
   ModelRenderer StockLower;
   ModelRenderer TopRails;
   ModelRenderer ScopeAdjust;
   ModelRenderer ScopeMount2;
   ModelRenderer BarrelBigPartFront;
   ModelRenderer Scope01;
   ModelRenderer Scope02;
   ModelRenderer Scope03;
   ModelRenderer Receiver;
   ModelRenderer ScopeMount;
   ModelRenderer ScopeAdjust2;
   ModelRenderer ScopeMiddle;
   ModelRenderer Muzzle01;
   ModelRenderer Muzzle04;
 
 public ModelAS50()
 {
   textureWidth = 256;
   textureHeight = 128;
   
     Grip1 = new ModelRenderer(this, 73, 37);
     Grip1.addBox(0F, 0F, 0F, 3, 9, 4);
     Grip1.setRotationPoint(-2F, 2F, 6F);
     Grip1.setTextureSize(256, 128);
     Grip1.mirror = true;
     setRotation(Grip1, 0.4461433F, 0F, 0F);
     Trigger01 = new ModelRenderer(this, 96, 32);
     Trigger01.addBox(0F, 0F, 0F, 2, 1, 6);
     Trigger01.setRotationPoint(-1.5F, 4F, 2F);
     Trigger01.setTextureSize(256, 128);
     Trigger01.mirror = true;
     setRotation(Trigger01, 0F, 0F, 0F);
     Trigger02 = new ModelRenderer(this, 96, 34);
     Trigger02.addBox(0F, 0F, 0F, 2, 2, 1);
     Trigger02.setRotationPoint(-1.5F, 2F, 2F);
     Trigger02.setTextureSize(256, 128);
     Trigger02.mirror = true;
     setRotation(Trigger02, 0F, 0F, 0F);
     MuzzleFront2 = new ModelRenderer(this, 0, 43);
     MuzzleFront2.addBox(0F, 0F, 0F, 1, 1, 1);
     MuzzleFront2.setRotationPoint(-0.5F, -4.88F, -66F);
     MuzzleFront2.setTextureSize(256, 128);
     MuzzleFront2.mirror = true;
     setRotation(MuzzleFront2, 0F, 0F, 0.7853982F);
     Magazine01 = new ModelRenderer(this, 52, 101);
     Magazine01.addBox(0F, 0F, 0F, 2, 2, 1);
     Magazine01.setRotationPoint(-1.5F, 7F, -0.5F);
     Magazine01.setTextureSize(256, 128);
     Magazine01.mirror = true;
     setRotation(Magazine01, 0F, 0F, 0F);
     Trigger03 = new ModelRenderer(this, 106, 34);
     Trigger03.addBox(0F, 0F, 0F, 1, 2, 1);
     Trigger03.setRotationPoint(-1F, 1.5F, 5F);
     Trigger03.setTextureSize(256, 128);
     Trigger03.mirror = true;
     setRotation(Trigger03, -0.2617994F, 0F, 0F);
     MagHolder = new ModelRenderer(this, 0, 99);
     MagHolder.addBox(0F, 0F, 0F, 3, 4, 13);
     MagHolder.setRotationPoint(-2F, -4F, -12F);
     MagHolder.setTextureSize(256, 128);
     MagHolder.mirror = true;
     setRotation(MagHolder, -0.0872665F, 0F, 0F);
     CheekRest = new ModelRenderer(this, 68, 3);
     CheekRest.addBox(0F, 0F, 0F, 4, 4, 16);
     CheekRest.setRotationPoint(-0.5F, -10F, 17F);
     CheekRest.setTextureSize(256, 128);
     CheekRest.mirror = true;
     setRotation(CheekRest, 0F, 0F, 0.7853982F);
     LowerTrigger = new ModelRenderer(this, 96, 40);
     LowerTrigger.addBox(0F, 0F, 0F, 3, 1, 13);
     LowerTrigger.setRotationPoint(-2F, 1F, 2F);
     LowerTrigger.setTextureSize(256, 128);
     LowerTrigger.mirror = true;
     setRotation(LowerTrigger, 0F, 0F, 0F);
     Magazine02 = new ModelRenderer(this, 34, 99);
     Magazine02.addBox(0F, 0F, 0F, 2, 8, 12);
     Magazine02.setRotationPoint(-1.5F, 0F, -11.5F);
     Magazine02.setTextureSize(256, 128);
     Magazine02.mirror = true;
     setRotation(Magazine02, 0F, 0F, 0F);
     Magazine03 = new ModelRenderer(this, 63, 100);
     Magazine03.addBox(0F, 0F, 0F, 2, 2, 11);
     Magazine03.setRotationPoint(-1.5F, 6F, -11F);
     Magazine03.setTextureSize(256, 128);
     Magazine03.mirror = true;
     setRotation(Magazine03, -0.0916298F, 0F, 0F);
     MidRailPart1 = new ModelRenderer(this, 0, 71);
     MidRailPart1.addBox(0F, 0F, 0F, 2, 1, 1);
     MidRailPart1.setRotationPoint(-1.5F, -10F, -17F);
     MidRailPart1.setTextureSize(256, 128);
     MidRailPart1.mirror = true;
     setRotation(MidRailPart1, 0F, 0F, 0F);
     UpperBarrel = new ModelRenderer(this, 69, 72);
     UpperBarrel.addBox(0F, 0F, 0F, 1, 1, 19);
     UpperBarrel.setRotationPoint(-0.5F, -9F, -48F);
     UpperBarrel.setTextureSize(256, 128);
     UpperBarrel.mirror = true;
     setRotation(UpperBarrel, 0F, 0F, 0.7853982F);
     BarrelBigPart = new ModelRenderer(this, 0, 65);
     BarrelBigPart.addBox(0F, 0F, 0F, 4, 4, 6);
     BarrelBigPart.setRotationPoint(-0.5F, -8.5F, -21F);
     BarrelBigPart.setTextureSize(256, 128);
     BarrelBigPart.mirror = true;
     setRotation(BarrelBigPart, 0F, 0F, 0.7853982F);
     Barrel = new ModelRenderer(this, 0, 24);
     Barrel.addBox(0F, 0F, 0F, 2, 2, 38);
     Barrel.setRotationPoint(-0.5F, -7F, -59F);
     Barrel.setTextureSize(256, 128);
     Barrel.mirror = true;
     setRotation(Barrel, 0F, 0F, 0.7853982F);
     ReceiverTop = new ModelRenderer(this, 0, 65);
     ReceiverTop.addBox(0F, 0F, 0F, 3, 1, 32);
     ReceiverTop.setRotationPoint(-2F, -9F, -15F);
     ReceiverTop.setTextureSize(256, 128);
     ReceiverTop.mirror = true;
     setRotation(ReceiverTop, 0F, 0F, 0F);
     BarrelBigPartTop = new ModelRenderer(this, 0, 20);
     BarrelBigPartTop.addBox(0F, 0F, 0F, 2, 2, 14);
     BarrelBigPartTop.setRotationPoint(-1.5F, -9F, -29F);
     BarrelBigPartTop.setTextureSize(256, 128);
     BarrelBigPartTop.mirror = true;
     setRotation(BarrelBigPartTop, 0F, 0F, 0F);
     ScopeMount4 = new ModelRenderer(this, 130, 0);
     ScopeMount4.addBox(0F, 0F, 0F, 3, 3, 1);
     ScopeMount4.setRotationPoint(-2F, -15F, 3F);
     ScopeMount4.setTextureSize(256, 128);
     ScopeMount4.mirror = true;
     setRotation(ScopeMount4, 0F, 0F, 0F);
     BarrelFrontPartBottom = new ModelRenderer(this, 0, 37);
     BarrelFrontPartBottom.addBox(0F, 0F, 0F, 2, 1, 2);
     BarrelFrontPartBottom.setRotationPoint(-1.5F, -4.5F, -61.5F);
     BarrelFrontPartBottom.setTextureSize(256, 128);
     BarrelFrontPartBottom.mirror = true;
     setRotation(BarrelFrontPartBottom, 0F, 0F, 0F);
     MidRailPart2 = new ModelRenderer(this, 0, 71);
     MidRailPart2.addBox(0F, 0F, 0F, 2, 1, 1);
     MidRailPart2.setRotationPoint(-1.5F, -10F, -26F);
     MidRailPart2.setTextureSize(256, 128);
     MidRailPart2.mirror = true;
     setRotation(MidRailPart2, 0F, 0F, 0F);
     MidRailPart3 = new ModelRenderer(this, 0, 71);
     MidRailPart3.addBox(0F, 0F, 0F, 2, 1, 1);
     MidRailPart3.setRotationPoint(-1.5F, -10F, -23F);
     MidRailPart3.setTextureSize(256, 128);
     MidRailPart3.mirror = true;
     setRotation(MidRailPart3, 0F, 0F, 0F);
     MidRailPart4 = new ModelRenderer(this, 0, 71);
     MidRailPart4.addBox(0F, 0F, 0F, 2, 1, 1);
     MidRailPart4.setRotationPoint(-1.5F, -10F, -20F);
     MidRailPart4.setTextureSize(256, 128);
     MidRailPart4.mirror = true;
     setRotation(MidRailPart4, 0F, 0F, 0F);
     MidRailPartTop = new ModelRenderer(this, 113, 24);
     MidRailPartTop.addBox(0F, 0F, 0F, 2, 1, 14);
     MidRailPartTop.setRotationPoint(-1.5F, -11F, -28F);
     MidRailPartTop.setTextureSize(256, 128);
     MidRailPartTop.mirror = true;
     setRotation(MidRailPartTop, 0F, 0F, 0F);
     MidRailPartFront = new ModelRenderer(this, 0, 71);
     MidRailPartFront.addBox(0F, 0F, 0F, 2, 3, 1);
     MidRailPartFront.setRotationPoint(-1.5F, -11F, -28F);
     MidRailPartFront.setTextureSize(256, 128);
     MidRailPartFront.mirror = true;
     setRotation(MidRailPartFront, -0.3228859F, 0F, 0F);
     BarrelMidPartTop = new ModelRenderer(this, 0, 56);
     BarrelMidPartTop.addBox(0F, 0F, 0F, 2, 3, 2);
     BarrelMidPartTop.setRotationPoint(-1.5F, -9F, -48F);
     BarrelMidPartTop.setTextureSize(256, 128);
     BarrelMidPartTop.mirror = true;
     setRotation(BarrelMidPartTop, -0.6707641F, 0F, 0F);
     BarrelMidPart01 = new ModelRenderer(this, 0, 55);
     BarrelMidPart01.addBox(0F, 0F, 0F, 3, 3, 3);
     BarrelMidPart01.setRotationPoint(-0.5F, -7.7F, -50F);
     BarrelMidPart01.setTextureSize(256, 128);
     BarrelMidPart01.mirror = true;
     setRotation(BarrelMidPart01, 0F, 0F, 0.7853982F);
     BarrelMidPartBottom = new ModelRenderer(this, 0, 37);
     BarrelMidPartBottom.addBox(0F, 0F, 0F, 2, 1, 2);
     BarrelMidPartBottom.setRotationPoint(-1.5F, -4.5F, -49.5F);
     BarrelMidPartBottom.setTextureSize(256, 128);
     BarrelMidPartBottom.mirror = true;
     setRotation(BarrelMidPartBottom, 0F, 0F, 0F);
     ScopeFront = new ModelRenderer(this, 129, 12);
     ScopeFront.addBox(0F, 0F, 0F, 5, 5, 5);
     ScopeFront.setRotationPoint(-0.5F, -19F, -18F);
     ScopeFront.setTextureSize(256, 128);
     ScopeFront.mirror = true;
     setRotation(ScopeFront, 0F, 0F, 0.7853982F);
     BarrelFrontPart01 = new ModelRenderer(this, 0, 55);
     BarrelFrontPart01.addBox(0F, 0F, 0F, 3, 3, 3);
     BarrelFrontPart01.setRotationPoint(-0.5F, -7.7F, -62F);
     BarrelFrontPart01.setTextureSize(256, 128);
     BarrelFrontPart01.mirror = true;
     setRotation(BarrelFrontPart01, 0F, 0F, 0.7853982F);
     MuzzleFront3 = new ModelRenderer(this, 5, 41);
     MuzzleFront3.addBox(0F, 0F, 0F, 3, 3, 1);
     MuzzleFront3.setRotationPoint(-0.5F, -7.7F, -67F);
     MuzzleFront3.setTextureSize(256, 128);
     MuzzleFront3.mirror = true;
     setRotation(MuzzleFront3, 0F, 0F, 0.7853982F);
     MuzzleFront = new ModelRenderer(this, 0, 43);
     MuzzleFront.addBox(0F, 0F, 0F, 1, 1, 1);
     MuzzleFront.setRotationPoint(-0.5F, -7.7F, -66F);
     MuzzleFront.setTextureSize(256, 128);
     MuzzleFront.mirror = true;
     setRotation(MuzzleFront, 0F, 0F, 0.7853982F);
     Muzzle05 = new ModelRenderer(this, 12, 46);
     Muzzle05.addBox(0F, 0F, 0F, 4, 4, 1);
     Muzzle05.setRotationPoint(-0.5F, -8.5F, -64F);
     Muzzle05.setTextureSize(256, 128);
     Muzzle05.mirror = true;
     setRotation(Muzzle05, 0F, 0F, 0.7853982F);
     UpperTrigger = new ModelRenderer(this, 45, 34);
     UpperTrigger.addBox(0F, 0F, 0F, 4, 3, 17);
     UpperTrigger.setRotationPoint(-2.5F, -2F, 0F);
     UpperTrigger.setTextureSize(256, 128);
     UpperTrigger.mirror = true;
     setRotation(UpperTrigger, 0F, 0F, 0F);
     StockBack02 = new ModelRenderer(this, 93, 0);
     StockBack02.addBox(0F, 0F, 0F, 5, 10, 1);
     StockBack02.setRotationPoint(-3F, -7F, 32F);
     StockBack02.setTextureSize(256, 128);
     StockBack02.mirror = true;
     setRotation(StockBack02, 0F, 0F, 0F);
     StockFlip = new ModelRenderer(this, 58, 0);
     StockFlip.addBox(0F, 0F, 0F, 3, 2, 10);
     StockFlip.setRotationPoint(-2F, 1F, 21F);
     StockFlip.setTextureSize(256, 128);
     StockFlip.mirror = true;
     setRotation(StockFlip, 0F, 0F, 0F);
     StockBack01 = new ModelRenderer(this, 117, 0);
     StockBack01.addBox(0F, 0F, 0F, 4, 10, 1);
     StockBack01.setRotationPoint(-2.5F, -7F, 31F);
     StockBack01.setTextureSize(256, 128);
     StockBack01.mirror = true;
     setRotation(StockBack01, 0F, 0F, 0F);
     StockLower = new ModelRenderer(this, 92, 0);
     StockLower.addBox(0F, 0F, 0F, 4, 5, 14);
     StockLower.setRotationPoint(-2.5F, -4F, 17F);
     StockLower.setTextureSize(256, 128);
     StockLower.mirror = true;
     setRotation(StockLower, 0F, 0F, 0F);
     TopRails = new ModelRenderer(this, 39, 68);
     TopRails.addBox(0F, 0F, 0F, 2, 2, 25);
     TopRails.setRotationPoint(-1.5F, -11F, -14F);
     TopRails.setTextureSize(256, 128);
     TopRails.mirror = true;
     setRotation(TopRails, 0F, 0F, 0F);
     ScopeAdjust = new ModelRenderer(this, 40, 9);
     ScopeAdjust.addBox(0F, 0F, 0F, 2, 3, 3);
     ScopeAdjust.setRotationPoint(-4.3F, -15.4F, -3.1F);
     ScopeAdjust.setTextureSize(256, 128);
     ScopeAdjust.mirror = true;
     setRotation(ScopeAdjust, 0.7853982F, 0F, 0F);
     ScopeMount2 = new ModelRenderer(this, 130, 0);
     ScopeMount2.addBox(0F, 0F, 0F, 3, 3, 1);
     ScopeMount2.setRotationPoint(-2F, -15F, -6F);
     ScopeMount2.setTextureSize(256, 128);
     ScopeMount2.mirror = true;
     setRotation(ScopeMount2, 0F, 0F, 0F);
     BarrelBigPartFront = new ModelRenderer(this, 0, 76);
     BarrelBigPartFront.addBox(0F, 0F, 0F, 4, 4, 8);
     BarrelBigPartFront.setRotationPoint(-0.5F, -8.5F, -29F);
     BarrelBigPartFront.setTextureSize(256, 128);
     BarrelBigPartFront.mirror = true;
     setRotation(BarrelBigPartFront, 0F, 0F, 0.7853982F);
     Scope01 = new ModelRenderer(this, 133, 23);
     Scope01.addBox(0F, 0F, 0F, 4, 4, 7);
     Scope01.setRotationPoint(-0.5F, -18.25F, 6F);
     Scope01.setTextureSize(256, 128);
     Scope01.mirror = true;
     setRotation(Scope01, 0F, 0F, 0.7853982F);
     Scope02 = new ModelRenderer(this, 150, 0);
     Scope02.addBox(0F, 0F, 0F, 3, 3, 14);
     Scope02.setRotationPoint(-0.5F, -17.5F, -8F);
     Scope02.setTextureSize(256, 128);
     Scope02.mirror = true;
     setRotation(Scope02, 0F, 0F, 0.7853982F);
     Scope03 = new ModelRenderer(this, 21, 0);
     Scope03.addBox(0F, 0F, 0F, 4, 4, 5);
     Scope03.setRotationPoint(-0.5F, -18.25F, -13F);
     Scope03.setTextureSize(256, 128);
     Scope03.mirror = true;
     setRotation(Scope03, 0F, 0F, 0.7853982F);
     Receiver = new ModelRenderer(this, 56, 23);
     Receiver.addBox(0F, 0F, 0F, 4, 6, 32);
     Receiver.setRotationPoint(-2.5F, -8F, -15F);
     Receiver.setTextureSize(256, 128);
     Receiver.mirror = true;
     setRotation(Receiver, 0F, 0F, 0F);
     ScopeMount = new ModelRenderer(this, 129, 0);
     ScopeMount.addBox(0F, 0F, 0F, 3, 1, 10);
     ScopeMount.setRotationPoint(-2F, -12F, -6F);
     ScopeMount.setTextureSize(256, 128);
     ScopeMount.mirror = true;
     setRotation(ScopeMount, 0F, 0F, 0F);
     ScopeAdjust2 = new ModelRenderer(this, 51, 13);
     ScopeAdjust2.addBox(0F, 0F, 0F, 3, 2, 3);
     ScopeAdjust2.setRotationPoint(-2.62F, -19.5F, -1F);
     ScopeAdjust2.setTextureSize(256, 128);
     ScopeAdjust2.mirror = true;
     setRotation(ScopeAdjust2, 0F, 0.7853982F, 0F);
     ScopeMiddle = new ModelRenderer(this, 40, 0);
     ScopeMiddle.addBox(0F, 0F, 0F, 4, 4, 4);
     ScopeMiddle.setRotationPoint(-2.3F, -17.5F, -3F);
     ScopeMiddle.setTextureSize(256, 128);
     ScopeMiddle.mirror = true;
     setRotation(ScopeMiddle, 0F, 0F, 0F);
     Muzzle01 = new ModelRenderer(this, 0, 46);
     Muzzle01.addBox(0F, 0F, 0F, 4, 4, 1);
     Muzzle01.setRotationPoint(-0.5F, -8.5F, -65F);
     Muzzle01.setTextureSize(256, 128);
     Muzzle01.mirror = true;
     setRotation(Muzzle01, 0F, 0F, 0.7853982F);
     Muzzle04 = new ModelRenderer(this, 0, 46);
     Muzzle04.addBox(0F, 0F, 0F, 4, 4, 1);
     Muzzle04.setRotationPoint(-0.5F, -8.5F, -63F);
     Muzzle04.setTextureSize(256, 128);
     Muzzle04.mirror = true;
     setRotation(Muzzle04, 0F, 0F, 0.7853982F);
 }
 
 @Override
 public void render(Entity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scale, int ammoLeft, float reloadProgress,
 		TransformType transformType, int part, float fireProgress, float chargeProgress) {

   Grip1.render(scale);
   Trigger01.render(scale);
   Trigger02.render(scale);
   MuzzleFront2.render(scale);
   Magazine01.render(scale);
   Trigger03.render(scale);
   MagHolder.render(scale);
   CheekRest.render(scale);
   LowerTrigger.render(scale);
   Magazine02.render(scale);
   Magazine03.render(scale);
   MidRailPart1.render(scale);
   UpperBarrel.render(scale);
   BarrelBigPart.render(scale);
   Barrel.render(scale);
   ReceiverTop.render(scale);
   BarrelBigPartTop.render(scale);
   ScopeMount4.render(scale);
   BarrelFrontPartBottom.render(scale);
   MidRailPart2.render(scale);
   MidRailPart3.render(scale);
   MidRailPart4.render(scale);
   MidRailPartTop.render(scale);
   MidRailPartFront.render(scale);
   BarrelMidPartTop.render(scale);
   BarrelMidPart01.render(scale);
   BarrelMidPartBottom.render(scale);
   ScopeFront.render(scale);
   BarrelFrontPart01.render(scale);
   MuzzleFront3.render(scale);
   MuzzleFront.render(scale);
   Muzzle05.render(scale);
   UpperTrigger.render(scale);
   StockBack02.render(scale);
   StockFlip.render(scale);
   StockBack01.render(scale);
   StockLower.render(scale);
   TopRails.render(scale);
   ScopeAdjust.render(scale);
   ScopeMount2.render(scale);
   BarrelBigPartFront.render(scale);
   Scope01.render(scale);
   Scope02.render(scale);
   Scope03.render(scale);
   Receiver.render(scale);
   ScopeMount.render(scale);
   ScopeAdjust2.render(scale);
   ScopeMiddle.render(scale);
   Muzzle01.render(scale);
   Muzzle04.render(scale);
 }
}